# defaults parameter ranges for all mappable synth parameters

# Numerical note length
note_length: [1e-2, 30.]
note_length_unit: 'seconds'

# define the note volume envelope applied to the samples
# A,D,S & R correspond to 'attack', 'decay', 'sustain' and 'release'
volume_envelope:
  A: [1e-2, 20.]
  D: [1e-2, 20.]
  S: [0., 1.]
  R: [1e-2, 20]
  Ac: [-1. ,1.]
  Dc: [-1. ,1.]
  Rc: [-1. ,1.]
  level: [0., 1.]
  A_unit: 'seconds'
  D_unit: 'seconds'
  S_unit: 'unitless'
  R_unit: 'seconds'
  Ac_unit: 'unitless'
  Dc_unit: 'unitless'
  Rc_unit: 'unitless'
  level_unit: 'unitless'    
  
# filter cutoff 
cutoff: [0., 1.]
cutoff_unit: 'unitless'

# Master volume
volume: [0., 1.]
volume_unit: 'unitless' 

# frequency limits in Hz
min_freq: [20,2.2e4]
max_freq: [20,2.2e4]
min_freq_unit: 'Hz'
max_freq_unit: 'Hz'

# Default pitch selection
pitch: [0,1.]
pitch_unit: 'unitless'

# center panning:
phi: [0., 1.]
phi_unit: 'half-cycles (π)'
theta: [0.,1.]
theta_unit: 'cycles (2π)'

# pitch range and default shift in semitones
pitch_shift: [0., 24.]
pitch_shift_unit: 'semitones'

# Do we apply a filter, and if so specify the cutoff and filter type
filter: "off"
filter_type: "LPF1"
cutoff: 1.

# or 'vibrato'
pitch_lfo:
  amount: [0, 2] 
  freq: [1,12]
  freq_shift: [0,3]
  A: [1e-2, 10]
  D: [1e-2, 10]
  S: [0, 1]
  R: [1e-2, 10]
  freq_unit: "Hz"
  amount_unit: "semitones"	

volume_lfo:
  amount: [0, 1] 
  freq: [1,12]
  freq_shift: [0,3]
  A: [1e-2, 10]
  D: [1e-2, 10]
  S: [0, 1]
  R: [1e-2, 10]
  freq_unit: "Hz"
  amount_unit: "fraction"	

  use: off
  wave: 'sine'
  amount: 0.5
  freq: 3
  freq_shift: 0
  phase: 'random'
  A: 0.
  D: 0.1
  S: 1.
  R: 0.
  Ac: 0.
  Dc: 0.
  Rc: 0.
  level: 1

_meta:
  note_length: >-
    Numerical note length 
  note_length_units: >-
    Units for numerical note length, e.g. seconds
  volume_envelope: >-
    define the note volume envelope applied to the samples
    A,D,S & R correspond to 'attack', 'decay', 'sustain' and 'release'
  volume_envelope:
    A: Attack
    D: Decay
    S: Sustain
    R: Release
    Ac: ""
    Dc: ""
    Rc: ""
    level: ""
    A_unit: units for Attack
    D_unit: units for Decay
    S_unit: units for Sustain
    R_unit: units for Release
    Ac_unit: units for Ac
    Dc_unit: units for Dc
    Rc_unit: units for Rc
    level_unit: units for level
  cutoff: filter cutoff
  cutoff_unit: units for filter cutoff
  volume: Master volume
  volume_unit: Units for master volume
  min_freq: Minimum frequency
  max_freq: Maximum frequency
  min_freq_unit: Units for minimum frequency
  max_freq_unit: Units for maximum frequency
  pitch: Default pitch selection
  pitch_unit: Units for Default pitch selection
  phi: phi coordinate for center panning
  phi_unit: units for phi coordinate for center panning
  theta: theta coordinate for center panning
  theta_unit: units for theta coordinate for center panning
  pitch_shift: default shift in semitones
  pitch_shift_unit: units for default shift in semitones

