#
# defaults for all synth parameters, mappable parameter ranges in ./parameter_ranges/default.yml
#

# preset name
name: "default"

# full description
description: >-
  Default preset for the synthesizer, using three saw wave oscillators,
  two of which are detuned slightly higher and lower respectively, with
  lower volumes. This gives a harmonically rich sound, suitable for
  filtering, with detuned unison saws removing some harshness.

# Numerical note length in s
note_length: 0.1

# define the note volume envelope applied to the samples
# A,D,S & R correspond to 'attack', 'decay', 'sustain' and 'release'
volume_envelope:
  A: 0.
  D: 0.1
  S: 1.
  R: 0.
  Ac: 0.
  Dc: 0.
  Rc: 0.
  level: 1.
  
# Do we apply a filter, and if so specify the cutoff and filter type
filter: "off"
filter_type: "LPF1"
cutoff: 1.

# or 'vibrato'
pitch_lfo:
  use: off
  wave: 'sine'
  amount: 0.5
  freq: 3
  freq_shift: 0
  phase: 'random'
  A: 0.
  D: 0.1
  S: 1.
  R: 0.
  Ac: 0.
  Dc: 0.
  Rc: 0.
  level: 1

# or 'tremolo'
volume_lfo:
  use: off
  wave: 'sine'
  amount: 0.5
  freq: 3
  freq_shift: 0
  phase: 'random'
  A: 0.
  D: 0.1
  S: 1.
  R: 0.
  Ac: 0.
  Dc: 0.
  Rc: 0.
  level: 1

# Master volume
volume: 1.

# how to interpolate and resample the spectrum
# "sample": interpolate spectrum values directly
# "preserve_power": integrate, interpolate then diff to avoid missing power in narrow features
interpolation_type: 'sample' 

# For an evolving spectrum, do we regenerate phases for each buffer, or keep the same?
# These have differing effects 
regen_phases: true

# Whether or not to generate IFFT such that the spectrum sample points are hit exactly 
fit_spec_multiples: true

# frequency limits in Hz
min_freq: 50.
max_freq: 2000.

# Default pitch selection
pitch: 1.

# center panning:
azimuth: 0.
polar: 0

# pitch range and default shift in semitones
pitch_hi: 0.1
pitch_lo: 0
pitch_shift: 0.

_meta:
  name: preset name
  description: full description
  note_length: >-
    Numerical note length in s
  volume_envelope: >-
    Define the note volume envelope applied to the samples.
    A,D,S & R correspond to 'attack', 'decay', 'sustain' and 'release'.
  volume_envelope:
    A: Attack
    D: Decay
    S: Sustain
    R: Release
    Ac: ""
    Dc: ""
    Rc: ""
    level: ""
  filter: >-
    Do we apply a filter?
  filter_type: >-
    filter type
  cutoff: >-
    filter cutoff
  pitch_lfo: >-
    or apply 'vibrato'?
  pitch_lfo:
    use: switch feature on or off
    wave: type of waveform
    amount: amount
    freq: frequency
    freq_shift: frequency shift
    phase: random
    A: Attack
    D: Decay
    S: Sustain
    R: Release
    Ac: ""
    Dc: ""
    Rc: ""
    level: ""
  volume_lfo: >-
    or apply 'tremolo'?
  volume_lfo:
    use: switch feature on or off
    wave: type of waveform
    amount: amount
    freq: frequency
    freq_shift: frequency shift
    phase: random
    A: Attack
    D: Decay
    S: Sustain
    R: Release
    Ac: ""
    Dc: ""
    Rc: ""
    level: ""
  volume: >-
    Master Volume
  interpolation_type: >-
    How to interpolate and resample in the spectrum. "sample": interpolate spectrum values directly; "preserve_power": integrate, interpolate then differentiate to avoid missing power in narrow features.
  regen_phases: >-
    For an evolving spectrum, do we regenerate phases for each buffer, or keep the same? These have differing effects.
  fit_spec_multiples: >-
    Whether or not to generate IFFT such that the spectrum sample points are hit exactly.
  min_freq: >-
    Minimum frequency in Hz
  max_freq: >-
    Maximum frequency in Hz
  pitch: >-
    Default pitch selection
  azimuth: >-
    azimuth coordinate for center panning
  polar: >-
    polar coordinate for center panning
  pitch_hi: >-
    pitch range maximum in semitones
  pitch_lo: >-
    pitch range minimum in semitones
  pitch_shift: >-   
    default shift in semitones

