#
# defaults for all synth parameters, mappable parameter ranges in ./parameter_ranges/default.yml
#

# preset name
name: "default"

# full description
description: >-
  Default preset for the synthesizer, using three saw wave oscillators,
  two of which are detuned slightly higher and lower respectively, with
  lower volumes. This gives a harmonically rich sound, suitable for
  filtering, with detuned unison saws removing some harshness.

# Numerical note length in s
note_length: 0.1

# define the note volume envelope applied to the samples
# A,D,S & R correspond to 'attack', 'decay', 'sustain' and 'release'
volume_envelope:
  A: 0.
  D: 0.1
  S: 1.
  R: 0.
  Ac: 0.
  Dc: 0.
  Rc: 0.
  level: 1.
  
# Do we apply a filter, and if so specify the cutoff and filter type
filter: "off"
filter_type: "LPF1"
cutoff: 1.

# or 'vibrato'
pitch_lfo:
  use: off
  wave: 'sine'
  amount: 0.5
  freq: 3
  freq_shift: 0
  phase: 'random'
  A: 0.
  D: 0.1
  S: 1.
  R: 0.
  Ac: 0.
  Dc: 0.
  Rc: 0.
  level: 1

# or 'tremolo'
volume_lfo:
  use: off
  wave: 'sine'
  amount: 0.5
  freq: 3
  freq_shift: 0
  phase: 'random'
  A: 0.
  D: 0.1
  S: 1.
  R: 0.
  Ac: 0.
  Dc: 0.
  Rc: 0.
  level: 1

# Master volume
volume: 1.

# how to interpolate and resample the spectrum
# "sample": interpolate spectrum values directly
# "preserve_power": integrate, interpolate then diff to avoid missing power in narrow features
interpolation_type: 'sample' 

# For an evolving spectrum, do we regenerate phases for each buffer, or keep the same?
# These have differing effects 
regen_phases: true

# Whether or not to generate IFFT such that the spectrum sample points are hit exactly 
fit_spec_multiples: true

# Do we equalise the spectra for equal loudness?
equal_loudness_normalisation: false

# frequency limits in Hz
min_freq: 50.
max_freq: 2000.

# Default pitch selection
pitch: 1.

# center panning:
azimuth: 0.
polar: 0

# pitch range and default shift in semitones
pitch_hi: 0.1
pitch_lo: 0
pitch_shift: 0.

