name: strauss
channels:
  - anaconda
dependencies:
  - python=3.8
  - pip
  - pip:
    - jupyterlab
    - ffmpeg_python
    - ipython
    - matplotlib
    - numpy
    - pandas
    - pychord
    - pyyaml
    - scipy
    - setuptools >= 4.2
    - sf2utils
    - sphinx
    - tqdm
    - "--editable=git+https://github.com/nateshmbhat/pyttsx3.git"
    - pyttsx3
    - wavio
    - wheel
    - sounddevice