# defaults for all sampler parameters

# preset name
name: "default"

# full description
description: >-
  Default preset for the sampler, basic setup with no looping, and
  an on-off volume envelope.

# Numerical note length in s or "sample" for the sample length or "none"
# to last to the end of the 
note_length: "sample"

# "off" for no looping "forward" to loop forward "forwardback" to loop back and forth
looping: "off"
# If looping, start and end point of loop in seconds.
# If loop_end is longer than the sample, clip to end of the sample.
loop_start: 0.
loop_end:  10.

# define the note volume envelope applied to the samples
# A,D,S & R correspond to 'attack', 'decay', 'sustain' and 'release'
volume_envelope:
  A: 0.
  D: 0.
  S: 1.
  R: 0.
  Ac: 0.
  Dc: 0.
  Rc: 0.
  level: 1.
  
# Do we apply a filter, and if so specify the cutoff and filter type
filter: "off"
filter_type: "LPF1"
cutoff: 1.

# or 'vibrato'
pitch_lfo:
  use: off
  wave: 'saw'
  amount: 0.5
  freq: 4
  freq_shift: 0
  phase: 'random'
  A: 0.3
  D: 0.1
  S: 1.
  R: 0.
  Ac: 0.
  Dc: 0.
  Rc: 0.
  level: 1

# or 'tremolo'
volume_lfo:
  use: off
  wave: 'sine'
  amount: 0.5
  freq: 2
  freq_shift: 0
  phase: 'random'
  A: 0.3
  D: 0.1
  S: 1.
  R: 0.
  Ac: 0.
  Dc: 0.
  Rc: 0.
  level: 1

# Master Volume
volume: 1.

# Default pitch selection
pitch: 1.

# center panning:
azimuth: 0.
polar: 0

# pitch range and default shift in semitones
pitch_hi: 36
pitch_lo: 0
pitch_shift: 0.

_meta:
  _doc: >-
    The `Sampler` generator type can be used to modify and play audio samples (sound recordings) .
  name: Preset name
  description: Full description of the parameters selected for this preset, e.g. looping, volume and pitch envelopes, filters, etc.
  note_length: >-
    Numerical note length in seconds, or `'sample'` for the sample length, or `'none'`
    to last to the end of the sonification.
  looping: >-
    Option to play the sample on a loop. `'off'` for no looping `'forward'` to loop forwards, `'forwardback'` to play the loop back and forth
  loop_start: >-
    If looping, starting point of loop in seconds.
  loop_end: >-
    If looping, ending point of loop in seconds. If loop_end is longer than the sample, clip to end of the sample.
  volume_envelope:
    _doc: >-
      Define the note volume envelope applied to the samples
    A: Attack, how long it takes for a tone to sound after it’s triggered
    D: Decay, how long it takes for the tones attack to die down after it’s triggered
    S: Sustain, the volume/level of the sound while it’s being triggered
    R: Release, how long the tone takes to go silent after the trigger is released
    Ac: Curvature of the attack portion of a note. Values from -1 to 1, positive indicates increases quickly then slow,
        negative slowly then quick. a value of 0 is a linear attack, increasing in volume at a constant rate.
    Dc: Curvature of the Decay portion of a note. Values from -1 to 1, positive indicates decreases quickly then slow,
        negative slowly then quick. a value of 0 is a linear decay, decreasing in volume at a constant rate.
    Rc: Curvature of the release portion of a note. Values from -1 to 1, positive indicates decreases quickly then slow,
        negative slowly then quick. a value of 0 is a linear release, decreasing in volume at a constant rate.
    level: Total amplitude level of the envelope from 0 to 1, contolling maximum volume of the note.
  filter: >-
    Apply a frequency filter to to the audio signal. Values are 'on' or 'off'. A filter affects the timbre by filtering out certain harmonics
  filter_type: >-
    Low pass filter (only allows frequencies lower than your cutoff to pass through)
    High pass filter (only allows frequencies higher than your cutoff to pass through)
  cutoff: >-
    The cutoff frequency (or `'knee'`) of the filter, beyond which frequencies are attenuated. as a fraction of the maximum frequency
  pitch_lfo:
    _doc: >-
      Controls for the `'Low Frequency Oscillator'` (LFO) used to modulate pitch of notes at rhythmic
        frequencies. In music this is often referred to a `'vibrato'`.
    use: switch feature on or off
    wave: Type of waveform used for the oscillator. As with `Synthesizer` oscillators can be sawtooth
        (`'saw'`), square (`'square'`), sinusoid (`'sine'`), triangle (`'tri'`) or noise (`'noise'`).
    amount: the amplitude of the maximal pitch oscillation from the underlying pitch
    freq: Base frequency of the LFO oscillations.
    freq_shift: Shift relative to the base LFO frequency.
    phase: The phase of the LFO oscillations, defined in terms of fraction of a whole cycle
    A: Attack, how long it takes for a tone to sound after it’s triggered
    D: Decay, how long it takes for the tone’s attack to die down after it’s triggered
    S: Sustain, the volume/level of the sound while it’s being triggered
    R: Release, how long the tone takes to go silent after the trigger is released
    Ac: Curvature of the attack portion of a note. Values from -1 to 1, positive indicates increases quickly then slow,
        negative slowly then quick. a value of 0 is a linear attack, increasing in volume at a constant rate.
    Dc: Curvature of the Decay portion of a note. Values from -1 to 1, positive indicates decreases quickly then slow,
        negative slowly then quick. a value of 0 is a linear decay, decreasing in volume at a constant rate.
    Rc: Curvature of the release portion of a note. Values from -1 to 1, positive indicates decreases quickly then slow,
        negative slowly then quick. a value of 0 is a linear release, decreasing in volume at a constant rate.
    level: Total amplitude level of the envelope from 0 to 1, contolling maximum volume of the note.
  volume_lfo:
    _doc: >-
      Controls for the `'Low Frequency Oscillator'` (LFO) used to modulate volume of notes at rhythmic
        frequencies. In music this is often referred to as `'tremolo'`.
    use: switch volume LFO effects on or off
    wave: Type of waveform used for the oscillator. As with `Synthesizer` oscillators can be sawtooth
        (`'saw'`), square (`'square'`), sinusoid (`'sine'`), triangle (`'tri'`) or noise (`'noise'`).
    amount: the amplitude of the maximal pitch oscillation from the underlying pitch
    freq: Base frequency of the LFO oscillations.
    freq_shift: Shift relative to the base LFO frequency
    phase: The phase of the LFO oscillations, defined in terms of fraction of a whole cycle.
    A: Attack, how long it takes for a tone to sound after it’s triggered
    D: Decay, how long it takes for the tone’s attack to die down after it’s triggered
    S: Sustain, the volume/level of the sound while it’s being triggered
    R: Release, how long the tone takes to go silent after the trigger is released
    Ac: Curvature of the attack portion of a note. Values from -1 to 1, positive indicates increases quickly then slow,
        negative slowly then quick. a value of 0 is a linear attack, increasing in volume at a constant rate.
    Dc: Curvature of the Decay portion of a note. Values from -1 to 1, positive indicates decreases quickly then slow,
        negative slowly then quick. a value of 0 is a linear decay, decreasing in volume at a constant rate.
    Rc: Curvature of the release portion of a note. Values from -1 to 1, positive indicates decreases quickly then slow,
        negative slowly then quick. a value of 0 is a linear release, decreasing in volume at a constant rate.
    level: Total amplitude level of the envelope from 0 to 1, contolling maximum volume of the note
  volume: >-
    Master Volume of generator.
  pitch: >-
    Default pitch selection (used by all generators)
  azimuth: >-
    azimuth coordinate for spatialising audio into differing channels
  polar: >-
    polar coordinate for spatialising audio into differing channels
  pitch_hi: >-
    pitch range maximum in semitones
  pitch_lo: >-
    pitch range minimum in semitones
  pitch_shift: >-   
    default shift in semitones

