#
# defaults for all synth parameters, mappable parameter ranges in ./parameter_ranges/default.yml
#

# preset name
name: "default"

# full description
description: >-
  Default preset for the synthesizer, using three saw wave oscillators,
  two of which are detuned slightly higher and lower respectively, with
  lower volumes. This gives a harmonically rich sound, suitable for
  filtering, with detuned unison saws removing some harshness.

# oscillator information
oscillators:
  # oscillator are denoted osc<n> with n=3 by default
  #
  # level: the intrinsic volume
  #
  # detune: the change in tuning as a percentage of the input frequency
  #
  # form: the waveform, choose from:
  # ['saw', 'square', 'sine', 'tri', 'noise']
  #
  osc1:
    form: 'saw'
    level: 1.
    detune: 0.
    phase: 0
  osc2:
    form: 'saw'
    level: 0.5
    detune: 0.75
    phase: 0.3
  osc3:
    form: 'saw'
    level: 0.5
    detune: 0.75
    phase: 0.6

# Numerical note length in s
note_length: 0.1

# define the note volume envelope applied to the samples
# A,D,S & R correspond to 'attack', 'decay', 'sustain' and 'release'
volume_envelope:
  A: 0.
  D: 0.1
  S: 1.
  R: 0.
  Ac: 0.
  Dc: 0.
  Rc: 0.
  level: 1.
  
# Do we apply a filter, and if so specify the cutoff and filter type
filter: "off"
filter_type: "LPF1"
cutoff: 1.

# or 'vibrato'
pitch_lfo:
  use: off
  wave: 'sine'
  amount: 0.5
  freq: 3
  freq_shift: 0
  phase: 'random'
  A: 0.
  D: 0.1
  S: 1.
  R: 0.
  Ac: 0.
  Dc: 0.
  Rc: 0.
  level: 1

# or 'tremolo'
volume_lfo:
  use: off
  wave: 'sine'
  amount: 0.5
  freq: 3
  freq_shift: 0
  phase: 'random'
  A: 0.
  D: 0.1
  S: 1.
  R: 0.
  Ac: 0.
  Dc: 0.
  Rc: 0.
  level: 1


# Master volume
volume: 1.

# Default pitch selection
pitch: 1.

# center panning:
azimuth: 0.
polar: 0

# pitch range and default shift in semitones
pitch_hi: 0.1
pitch_lo: 0
pitch_shift: 0.

_meta:
  _doc: >-
    The `Synth` generator type can be used to synthesise sound using mathematically
    generated waveforms or `oscillators`. The preset can be used to modify the relative
    frequency, phase and amplitude of these oscillators.
  name: Name of the preset
  description: Full description of the preset purpose and parameters.
  oscillators:
    _doc: >-
      Oscillator information. Oscillator are denoted osc<n> with n=3 by default.
    osc1:
      form: Type of waveform used for oscillator 1, choose from ['saw', 'square', 'sine', 'tri', 'noise']
      level: Amplitude of the oscillator from 0 to 1, contolling maximum volume of the note
      detune: Change in tuning as a percentage of the input frequency
      phase: The phase of the oscillator, defined in terms of fraction of a whole cycle
    osc2:
      form: Type of waveform used for oscillator 2, choose from ['saw', 'square', 'sine', 'tri', 'noise']
      level: Amplitude of the oscillator from 0 to 1, contolling maximum volume of the note
      detune: Change in tuning as a percentage of the input frequency
      phase: The phase of the oscillator, defined in terms of fraction of a whole cycle
    osc3:
      form: Type of waveform used for oscillator 3, choose from ['saw', 'square', 'sine', 'tri', 'noise']
      level: Amplitude of the oscillator from 0 to 1, contolling maximum volume of the note
      detune: Change in tuning as a percentage of the input frequency
      phase: The phase of the oscillator, defined in terms of fraction of a whole cycle

  note_length: >-
    Numerical note length in seconds
  volume_envelope: >-
    Define the note volume envelope applied to the samples.
    A,D,S & R correspond to 'attack', 'decay', 'sustain' and 'release'.
  volume_envelope:
    A: Attack, how long it takes for a tone to sound after it’s triggered
    D: Decay, how long it takes for the tone’s attack to die down after it’s triggered
    S: Sustain, the volume/level of the sound while it’s being triggered
    R: Release, how long the tone takes to go silent after the trigger is released
    Ac: >-
        "Curvature" of the attack portion of a note. Values from -1 to 1, positive indicates increases quickly then slow,
        negative slowly then quick. a value of 0 is a linear attack, increasing in volume at a constant rate.
    Dc: >-
        "Curvature" of the Decay portion of a note. Values from -1 to 1, positive indicates decreases quickly then slow,
        negative slowly then quick. a value of 0 is a linear decay, decreasing in volume at a constant rate.
    Rc: >-
        "Curvature" of the release portion of a note. Values from -1 to 1, positive indicates decreases quickly then slow,
        negative slowly then quick. a value of 0 is a linear release, decreasing in volume at a constant rate.

    level: Total amplitude level of the envelope from 0 to 1, contolling maximum volume of the note
  filter: >-
    Do we apply a frequency filter to the audio signal? This can be used to change the balance of frequencies and manipulate the 'timbre' of a note
  filter_type: >-
    Choose from available filter types 
  cutoff: >-
    The cut-off frequency (or `knee`) of the filter, beyond which frequencies are attenuated.
    Specified between 0 and 1 as a fraction of the audible range of notes we can hear (E0 to D#10). 
  pitch_lfo:
    _doc: >-
        Controls for the 'Low Frequency Oscillator' (LFO) used to modulate pitch of notes at rhythmic
        frequencies. In music this is often referred to a 'vibrato'   
    use: Switch pitch LFO effects on or off
    wave: >-
        Type of waveform used for the oscillator. As with `Synthesizer` oscillators can be sawtooth
        (`'saw'`), square (`'square'`), sinusoid (`'sine'`), triangle (`'tri'`) or noise (`'noise'`).
    amount: The amplitude of the maximal pitch oscillation from the underlying pitch
    freq: Base frequency of the LFO oscillations.
    freq_shift: Shift relative to the bae LFO frequency
    phase: The phase of the LFO oscillations, defined in terms of fraction of a whole cycle
    A: Attack, how long it takes for a tone to sound after it’s triggered
    D: Decay, how long it takes for the tone’s attack to die down after it’s triggered
    S: Sustain, the volume/level of the sound while it’s being triggered
    R: Release, how long the tone takes to go silent after the trigger is released
    Ac: >-
        "Curvature" of the attack portion of a note. Values from -1 to 1, positive indicates increases quickly then slow, negative slowly then quick. a value of 0 is a linear attack, increasing in volume at a constant rate.
    Dc: >-
        "Curvature" of the Decay portion of a note. Values from -1 to 1, positive indicates decreases quickly then slow, negative slowly then quick. a value of 0 is a linear decay, decreasing in volume at a constant rate.
    Rc: >-
        "Curvature" of the release portion of a note. Values from -1 to 1, positive indicates decreases quickly then slow, negative slowly then quick. a value of 0 is a linear release, decreasing in volume at a constant rate.

    level: Total amplitude level of the envelope from 0 to 1, contolling maximum volume of the note
  volume_lfo:
    _doc: >-
        Controls for the 'Low Frequency Oscillator' (LFO) used to modulate volume of notes at rhythmic
        frequencies. In music this is often referred to as 'tremolo'.
    use: Switch pitch LFO effects on or off
    wave: >-
        Type of waveform used for the oscillator. As with `Synthesizer` oscillators can be sawtooth
        (`'saw'`), square (`'square'`), sinusoid (`'sine'`), triangle (`'tri'`) or noise (`'noise'`).
    amount: the amplitude of the maximal pitch oscillation from the underlying pitch
    freq: Base frequency of the LFO oscillations.
    freq_shift: shift relative to the bae LFO frequency
    phase: The phase of the LFO oscillations, defined in terms of fraction of a whole cycle
    A: Attack, how long it takes for a tone to sound after it’s triggered
    D: Decay, how long it takes for the tone’s attack to die down after it’s triggered
    S: Sustain, the volume/level of the sound while it’s being triggered
    R: Release, how long the tone takes to go silent after the trigger is released
    Ac: >-
        "Curvature" of the attack portion of a note. Values from -1 to 1, positive indicates increases quickly then slow, negative slowly then quick. a value of 0 is a linear attack, increasing in volume at a constant rate.
    Dc: >-
        "Curvature" of the Decay portion of a note. Values from -1 to 1, positive indicates decreases quickly then slow, negative slowly then quick. a value of 0 is a linear decay, decreasing in volume at a constant rate.
    Rc: >-
        "Curvature" of the release portion of a note. Values from -1 to 1, positive indicates decreases quickly then slow, negative slowly then quick. a value of 0 is a linear release, decreasing in volume at a constant rate.
    level: Total amplitude level of the envelope from 0 to 1, contolling maximum volume of the note
  volume: >-
    Master Volume of synthesizer
  pitch: >-
    Default pitch selection
  azimuth: >-
    Azimuth coordinate for spatialising audio into differing channels
  polar: >-
    Polar coordinate for spatialising audio into differing channels
  pitch_hi: >-
    Pitch range maximum in semitones
  pitch_lo: >-
    Pitch range minimum in semitones
  pitch_shift: >-   
    Default shift in semitones

